Update patch set 1
Patch Set 1:

drivers/cpuidle/coupled.c:161:25: error: incompatible types when initializing type 'struct atomic_t *' using type 'atomic_t'

I think you forgot the pointer in line 113: atomic_t *barrier_pc;

Patch-set: 1