ANDROID: xt_quota2: Replace strlcpy() with compatible and safer variant strscpy()
strlcpy() has now been formally removed from the kernel due to the risks it poses.

Let's follow suit and convert over to strscpy().

Fixes the following build error:

  net/netfilter/xt_quota2.c:114:3: error:
    call to undeclared library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)';
      ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    114 |                 strlcpy(pm->prefix, prefix, sizeof(pm->prefix));

Fixes: d26270061ae6 ("string: Remove strlcpy()")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I33990ba6ddd60901f21ea1c6e60675c7c1262c54