ANDROID: sched: remove SMP-related ifdefs around proxy_exec fns
Commit cac5cefbade9 ("sched/smp: Make SMP unconditional") removed if
guards that used to be present around __move_queued_task_locked and
__task_is_pushable and their callers. Remove the equivalent ifdefs
around their wrappers to prevent the following kernelci build errors for
allnoconfig builds:

with gcc-14:
kernel/sched/core.c: In function ‘push_cpu_stop’:
kernel/sched/core.c:2856:17: error: implicit declaration of function ‘move_queued_task_locked’; did you mean ‘move_queued_task’? [-Wimplicit-function-declaration]
 2856 |                 move_queued_task_locked(rq, lowest_rq, p);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                 move_queued_task
  AR      kernel/power/built-in.a
  CC      kernel/sched/build_policy.o
make[4]: *** [scripts/Makefile.build:291: kernel/sched/core.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  CC      lib/debug_locks.o
  CC      lib/random32.o
  CC      fs/fs_struct.o
  CC      drivers/base/init.o
  AR      drivers/scsi/built-in.a
  CC      mm/mlock.o
  CC      kernel/locking/semaphore.o
  CC      mm/mmap.o
  COPY    drivers/tty/vt/defkeymap.c
  CC      lib/bust_spinlocks.o
  CC      drivers/base/map.o
  CC      lib/kasprintf.o
  CC      fs/statfs.o
  CC      io_uring/io-wq.o
  CC      kernel/printk/printk.o
  CC      kernel/printk/printk_safe.o
  AR      drivers/nvme/common/built-in.a
  AR      drivers/nvme/host/built-in.a
In file included from kernel/sched/build_policy.c:52:
kernel/sched/rt.c: In function ‘pick_highest_pushable_task’:
kernel/sched/rt.c:1846:21: error: implicit declaration of function ‘task_is_pushable’; did you mean ‘task_is_runnable’? [-Wimplicit-function-declaration]
 1846 |                 if (task_is_pushable(rq, p, cpu) == 1)
      |                     ^~~~~~~~~~~~~~~~
      |                     task_is_runnable
  AR      drivers/nvme/target/built-in.a
  AR      drivers/nvme/built-in.a
  CC      kernel/locking/rwsem.o
kernel/sched/rt.c: In function ‘push_rt_task’:
kernel/sched/rt.c:2231:9: error: implicit declaration of function ‘move_queued_task_locked’ [-Wimplicit-function-declaration]
 2231 |         move_queued_task_locked(rq, lowest_rq, next_task);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
  CC      kernel/irq/irqdesc.o

With clang-21:
kernel/sched/core.c:2856:3: error: call to undeclared function 'move_queued_task_locked'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2856 |                 move_queued_task_locked(rq, lowest_rq, p);
      |                 ^
kernel/sched/core.c:2856:3: note: did you mean '__move_queued_task_locked'?
kernel/sched/sched.h:3890:6: note: '__move_queued_task_locked' declared here
 3890 | void __move_queued_task_locked(struct rq *src_rq, struct rq *dst_rq, struct task_struct *task)
      |      ^
kernel/sched/core.c:8741:12: warning: array index -1 is before the beginning of the array [-Warray-bounds]
 8741 |                                        preempt_modes[preempt_dynamic_mode] : "undef",
      |                                        ^             ~~~~~~~~~~~~~~~~~~~~
kernel/sched/core.c:8716:1: note: array 'preempt_modes' declared here
 8716 | const char *preempt_modes[] = {
      | ^
1 warning and 1 error generated.
make[4]: *** [scripts/Makefile.build:291: kernel/sched/core.o] Error 1
make[3]: *** [scripts/Makefile.build:560: kernel/sched] Error 2
make[2]: *** [scripts/Makefile.build:560: kernel] Error 2
make[2]: *** Waiting for unfinished jobs....

Fixes: f77e29498767 ("ANDROID: sched: Fix rt/dl load balancing via chain level balance")
Reported-by: kernelci.org bot <bot@kernelci.org>
Change-Id: Ie5c79eed863632d619604af89511d39a382fea7f
Signed-off-by: Tiffany Yang <ynaffit@google.com>