ANDROID: dma-buf: Replicate function definition change to the exported prototype
Commit 310ec03841a3 ("dma-buf: align fd_flags and heap_flags with
dma_heap_allocation_data") changed the types of two of the function
parameters.  We need to replicate that change in the public prototype.

Fixes the following build error:

  drivers/dma-buf/dma-heap.c:79:17: error: conflicting types for 'dma_heap_buffer_alloc'
   79 | struct dma_buf *dma_heap_buffer_alloc(struct dma_heap *heap, size_t len,

Fixes: 310ec03841a3 ("dma-buf: align fd_flags and heap_flags with dma_heap_allocation_data")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I8c31917bf1b558f098296516d07e71d3fecea412