ANDROID: fix kernelci build-break due to GCC plugin issue
For the 32-bit ARM build of imx_v6_v7_defconfig+allmodconfig, GCC
plugins don't work properly for the gcc-12 (12.2.0) toolchain
used by kernelci.

Work around this issue by inhibiting the use of plugins for
32-bit ARM builds.

With GCC plugins enabled, 32-bit ARM builds of imx_v6_v7_defconfig+allmodconfig
fail with:

arm-linux-gnueabihf-ld: arch/arm/boot/compressed/atags_to_fdt.o: in function `atags_to_fdt':
atags_to_fdt.c:(.text.atags_to_fdt+0x18): undefined reference to `stackleak_track_stack'

Bug: 393580166
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Ic67fb5c89614f4dcc656df1da8b70fe1c016c559