ANDROID: kernel/kheaders: Tar actual kernel header files for bazel-built kernel
/sys/kernel/kheaders.tar.xz now contains mainly symlinks rather than
actual header files when built using bazel.
e.g.:
lrwxrwxrwx ./include/media/dvb_frontend.h -> /path/to/bazel_out/common/include/media/dvb_frontend.h
lrwxrwxrwx ./include/media/dvb_math.h -> /path/to/bazel_out/common/include/media/dvb_math.h

This causes bcc tools to fail compiling and running under adeb (android debian shell).

$ adeb shell /usr/share/bcc/tools/profile
fatal error: './include/linux/kconfig.h' file not found

so we just follow symlinks for kheaders.tar.xz.

Change-Id: I2d1c4e28b32e1a0116d34f2af9426403115b9d2d
Signed-off-by: Eric Yan <eric.yan@oppo.com>