ANDROID: ARM: Add missing include of kernel_stat.h
Fixes "error: implicit declaration of function 'kstat_irqs_cpu'".

Bug: 140053385
Change-Id: I442f8e82793305785ae7d416ba22935b4f3121b9
Signed-off-by: Eric Biggers <ebiggers@google.com>