ANDROID: mld: temporary workaround to fortify break
After merging the 'net-next-6.15' tag, a build failure was introduced in
the iwlwifi mld driver when building allmodconfig with clang:

  include/linux/fortify-string.h:719:4: error: call to '__read_overflow'
  declared with 'error' attribute: detected read beyond size of object
  (1st parameter)
    719 |                         __read_overflow();
        |                         ^
  1 error generated.

Kees pointed us to the same report at [1], where disabling loop unroll
via pragma was suggested as a workaround. Testing this locally confirmed
it resolved the build failure. Take the workaround until the underlying
issue gets resolved upstream.

Bug: 411091992
Link: https://github.com/ClangBuiltLinux/linux/issues/2076 [1]
Cc: Kees Cook <keescook@google.com>
Change-Id: I679110765adc13adcd0b25dcbc5c811bfada67ca
Signed-off-by: Carlos Llamas <cmllamas@google.com>