ANDROID: Protect Kunit & virtio modules
* This is to mark previously non marked modules as protected.
* This fixes the following error (while running `tools/bazel run //common:kernel_aarch64_abi_update` to update the ABI manually):
  ```
  ERROR: protected exports list must be updated before updating ABI definition. To update, execute 'tools/bazel run @@//common:kernel_aarch64_abi_update_protected_exports'.
  ```

Fixes: ce93918d6f19 ("ANDROID: GKI: enable options to run GKI as Microdroid guest")
Fixes: 22f9005179da ("ANDROID: Build GKI with CONFIG_KUNIT=m")
Bug: 287199267
Change-Id: I323c5ce23b6087ba94f497ae36ec68dc4fc11707
Signed-off-by: Ulises Mendez Martinez <umendez@google.com>