FROMLIST: libbpf: Fix implicit memfd_create() for bionic
Since memfd_create() is not consistently available across different
bionic libc implementations, using memfd_create() directly can break
some Android builds:

  tools/lib/bpf/linker.c:576:7: error: implicit declaration of function 'memfd_create' [-Werror,-Wimplicit-function-declaration]
    576 |         fd = memfd_create(filename, 0);
        |              ^

To fix this, relocate and inline the sys_memfd_create() helper so that
it can be used in "linker.c". Similar issues were previously fixed by
commit 9fa5e1a180aa ("libbpf: Call memfd_create() syscall directly").

Cc: Alastair Robertson <ajor@meta.com>
Cc: Andrii Nakryiko <andrii@kernel.org>
Fixes: 6d5e5e5d7ce1 ("libbpf: Extend linker API to support in-memory ELF files")
Signed-off-by: Carlos Llamas <cmllamas@google.com>

Bug: 407607209
Link: https://lore.kernel.org/all/20250330211325.530677-1-cmllamas@google.com/
Change-Id: I221b72f88bcdc7adfb4bb1a5964f71b525019457
Signed-off-by: Carlos Llamas <cmllamas@google.com>