ANDROID: mm: add vendor hook to bypass migration target
Previously, I've added vendor hook for same purpose via
https://android-review.googlesource.com/c/kernel/common/+/3253173.

But since change below was reverted, I'm getting build error while
using the vendor hook.

b511e79bc5ff ANDROID: Only warn on long symbols [Matthew Maurer]
https://android-review.googlesource.com/c/kernel/common/+/3136133.

bd197c334a65 ANDROID: revert Rust Binder changes in android15-6.6

ERROR: modpost: too long symbol
	"__tracepoint_android_vh_suitable_migration_target_bypass"

So I'd like to replace this vendor hook with shorter name.

Bug: 378012042
Change-Id: Ibed26c4d8a7ea9eb4d1900a16f15498267867f6b
Signed-off-by: Sooyong Suk <s.suk@samsung.corp-partner.google.com>