rust: harden index manipulation using ownership
Rust is very effective at preventing memory safety bugs such as
use-after-free bugs, but it is less effective at preventing bugs that
arise from using indices incorrectly. Accessing an array out of bounds
is caught and results in a kernel panic, but it is still possible to do
it. Accessing an array at the wrong index is not caught at all.

Unfortunately, the Android Binder driver has a component where it
"translates" the contents of transactions sent using the driver, which
involves complex and error-prone index manipulation. The C driver has
had several bugs in this area. A few examples:

4df153652cc4 ("binder: fix UAF caused by offsets overwrite")
bdc1c5fac982 ("binder: fix UAF caused by faulty buffer cleanup")
16981742717b ("binder: fix incorrect calculation for num_valid")
a56587065094 ("binder: Set end of SG buffer area properly.")

As mentioned above, Rust is not immune to these issues either. In fact,
I've already encountered and fixed two bugs like this in Rust Binder. In
both cases, the bugs could result in `Allocation::cleanup_object` calls
on invalid data. Rust's safety guarantees prevented these bugs from
affecting the integrity of kernel itself, but an attacker could use them
to e.g. manipulate handles that are present in other processes and for
example obtaining IApplicationThread handle belonging to another app
from system_server, which in turn allows loading code into that app.

Ultimately, the root cause of all of these bugs is that there is some
index in the destination buffer that gets written to twice.

The primary idea of this new Range API is to utilize Rust's ownership
semantics to prevent reuse of indices. The idea is that you create one
big Range for the entire range of indices, and then there are various
methods to split it into smaller ranges. An example from Rust Binder,
where several kinds of data are stored next to each other:

// Split the buffer size into sub-ranges.
let full_range = Range::new_area(len);
let (data_range, after_data) = full_range.split_within(aligned_data_size)?;
let (offsets_range, after_offsets) = after_data.split_within(aligned_offsets_size)?;
let (buffers_range, after_buffers) = after_offsets.split_within(aligned_buffers_size)?;
let (secctx_range, after_secctx) = after_buffers.split_within(aligned_secctx_size)?;
after_secctx.assert_empty()?;

The Range type is set up so that it cannot be copied or cloned, which
means that any attempts to use a Range more than once will fail to
compile. For example, if the line creating `buffers_range` accidentally
tried to split `after_data` instead of `after_offsets`, then that would
lead to this compilation error:

error[E0382]: use of moved value: `after_data`
    --> /usr/local/google/home/aliceryhl/rust-android-mainline/common/drivers/android/binder/thread.rs:1101:50
     |
1099 | let (data_range, after_data) = full_range.split_within(aligned_data_size)?;
     |                  ---------- move occurs because `after_data` has type `kernel::range::Range`, which does not implement the `Copy` trait
1100 | let (offsets_range, after_offsets) = after_data.split_within(aligned_offsets_size)?;
     |                                                 ---------------------------------- `after_data` moved due to this method call
1101 | let (buffers_range, after_buffers) = after_data.split_within(aligned_buffers_size)?;
     |                                      ^^^^^^^^^^ value used here after move
     |
note: `kernel::range::Range::split_within` takes ownership of the receiver `self`, which moves `after_data`
    --> /usr/local/google/home/aliceryhl/rust-android-mainline/common/rust/kernel/range.rs:108:29
     |
108  | pub fn split_within(mut self, length: usize) -> Result<(Range, Range), RangeError> {
     |                         ^^^^

Basically, the error says that you tried to use the `after_data` range
twice, which is not allowed because `split_within` destroys the object
you call it on.

In Rust Binder, I am using the ranges to prevent reuse of indices in the
*destination* buffer. To enforce that, all methods for writing to the
destination buffer are modified to take a `Range` as an argument,
consuming the range being written to. As ranges can only be split into
smaller pieces, this enforces that you will never write to the same
index twice.

Of course, the API is not completely bullet-proof. If you call
`Range::new_area` twice, you'll get two overlapping ranges. But we don't
need it to be completely impossible to misuse. It just needs to be
really difficult to do so accidentally.

Binder has one case where it intentionally writes to the same location
twice: when sending file descriptors over Binder, the driver does not
know what value the fd will have when transferring the data, so it will
first write u32::MAX. Much later, it will overwrite it with the real fd.
There is a `duplicate_range_careful` method for this case.

It is interesting to compare with the uaccess patchset [1]. The API that
Wedson and I introduced for reading from userspace also has some rather
similar logic to ensure that the same userspace address is never read
twice. This helps prevent time-of-check-to-time-of-use bugs where
userspace modifies the data in between two reads, which can cause bugs
if the driver assumes that the memory is unchanged.

In fact, both Rust Binder bugs mentioned earlier involve the uaccess API
refusing to accept the transaction. However, it still lead to a
vulnerability because, before the invalid data was discovered by the
uaccess API, previously translated data had gotten overwritten, which
lead to the `cleanup_object` routine doing the wrong thing.

This patchset is inspired by Benno's untrusted data patchset [2], which
explores a different way to write misuse-resistant APIs.

Link: https://lore.kernel.org/r/20240528-alice-mm-v7-0-78222c31b8f4@google.com [1]
Link: https://lore.kernel.org/r/20240913112643.542914-1-benno.lossin@proton.me [2]
Change-Id: I69c65338b7ed649d27a100a25701272aebf7508e
Signed-off-by: Alice Ryhl <aliceryhl@google.com>