ANDROID: Limit vfs-only namespace to GKI builds
The VFS namespace breaks several kenelci builds/tests. Limit the
namespace restrictions to GKI builds:

Example: build of multi_v5_defconfig:

ERROR: modpost: module configfs uses symbol kern_path from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Fixes: a38b207d4f4e ("ANDROID: GKI: set vfs-only exports into their own namespace")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I7e2c0a3fe561eb85e725e2fb611c6a2b0ee171e7