Update patch set 3
Patch Set 3: Code-Review-2

This is causing a warning on GCC and a build failure with clang:

In file included from <built-in>:2:
/usr/local/google/home/astrachan/android/master/kernel/common/lib/vdso/gettimeofday.c:144:25: error: initializing 'struct vdso_timestamp *' with an expression of type
      'const struct vdso_timestamp *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        struct vdso_timestamp *vdso_ts = &vd->basetime[CLOCK_REALTIME];
                               ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scripts/Makefile.build:334: recipe for target 'arch/arm64/kernel/vdso/vgettimeofday.o' failed
make[1]: *** [arch/arm64/kernel/vdso/vgettimeofday.o] Error 1
arch/arm64/Makefile:195: recipe for target 'vdso_prepare' failed
make: *** [vdso_prepare] Error 2

Patch-set: 3
Reviewer: Gerrit User 1293738 <1293738@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=-2
Label: Presubmit-Ready=0