ANDROID: GKI: Remove pfn_valid symbol
We are switching to the generic pfn_valid function and the
arm64-specific one is being removed.

ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - pfn_valid

Bug: 228454859
Change-Id: I8cc2d19aa2cb6e7639b2d1b08d0c67fc9c7c948e
Signed-off-by: Georgi Djakov <quic_c_gdjako@quicinc.com>