ANDROID: yukawa fix defconfig to be like .config
Some values in defconfig are set but isn't present in the final .config.
So we change them to be the value in .config.

Fixes the following errors when setting kernel_build(defconfig):

    ERROR: CONFIG_BRCMUTIL: actual '', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_BRCMFMAC: actual '', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_BRCMFMAC_PROTO_BCDC: actual '', expected 'y' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_BRCMFMAC_SDIO: actual '', expected 'y' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_COMMON_CLK_MESON_REGMAP: actual 'y', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_COMMON_CLK_MESON_DUALDIV: actual 'y', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_COMMON_CLK_MESON_MPLL: actual 'y', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_COMMON_CLK_MESON_PLL: actual 'y', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_COMMON_CLK_MESON_VID_PLL_DIV: actual 'y', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_MTD_NAND_MESON: actual '', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_MESON_EFUSE: actual '', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment
    ERROR: CONFIG_MESON_GX_PM_DOMAINS: actual '', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment

Bug: 236012223
Test: check that .config doesn't change before and after this CL.
Change-Id: I3685be705860d2694b3447ac932f6a59c6745652
Signed-off-by: HONG Yifan <elsk@google.com>