Update patch set 2
Patch Set 2:

seems it's this change that caused the fsnotify_parent related build failures, like reported here:
https://ci.linaro.org/job/lkft-gki-kernel/30/console

11:33:41 In file included from /home/buildslave/srv/lkft/workspace/common/fs/notify/fsnotify.c:15:
11:33:41 In file included from /home/buildslave/srv/lkft/workspace/common/fs/notify/fsnotify.h:6:
11:33:41 /home/buildslave/srv/lkft/workspace/common/include/linux/fsnotify.h:34:19: error: static declaration of 'fsnotify_parent' follows non-static declaration
11:33:41 static inline int fsnotify_parent(const struct path *path,
11:33:41                   ^
11:33:41 /home/buildslave/srv/lkft/workspace/common/include/linux/fsnotify_backend.h:382:12: note: previous declaration is here
11:33:41 extern int fsnotify_parent(struct dentry *dentry, __u32 mask, const void *data,
11:33:41            ^
11:33:41 In file included from /home/buildslave/srv/lkft/workspace/common/fs/notify/fsnotify.c:15:
11:33:41 In file included from /home/buildslave/srv/lkft/workspace/common/fs/notify/fsnotify.h:6:
11:33:41 /home/buildslave/srv/lkft/workspace/common/include/linux/fsnotify.h:40:9: error: implicit declaration of function '__fsnotify_parent' [-Werror,-Wimplicit-function-declaration]
11:33:41         return __fsnotify_parent(path, dentry, mask);
11:33:41                ^
11:33:41 /home/buildslave/srv/lkft/workspace/common/include/linux/fsnotify.h:40:9: note: did you mean 'fsnotify_parent'?
11:33:41 /home/buildslave/srv/lkft/workspace/common/include/linux/fsnotify_backend.h:382:12: note: 'fsnotify_parent' declared here
11:33:41 extern int fsnotify_parent(struct dentry *dentry, __u32 mask, const void *data,
11:33:41            ^
11:33:41 In file included from /home/buildslave/srv/lkft/workspace/common/fs/notify/fsnotify.c:15:
11:33:41 In file included from /home/buildslave/srv/lkft/workspace/common/fs/notify/fsnotify.h:6:
11:33:41 /home/buildslave/srv/lkft/workspace/common/include/linux/fsnotify.h:50:44: error: too few arguments to function call, expected 4, have 3
11:33:41         int ret = fsnotify_parent(path, NULL, mask);
11:33:41                   ~~~~~~~~~~~~~~~                 ^

Patch-set: 2
CC: Gerrit User 1055708 <1055708@85c56323-6fa9-3386-8a01-6480fb634889>
CC: Gerrit User 1010110 <1010110@85c56323-6fa9-3386-8a01-6480fb634889>
CC: Gerrit User 1293738 <1293738@85c56323-6fa9-3386-8a01-6480fb634889>
CC: Gerrit User 1052193 <1052193@85c56323-6fa9-3386-8a01-6480fb634889>
CC: Gerrit User 1090891 <1090891@85c56323-6fa9-3386-8a01-6480fb634889>
CC: Gerrit User 1069543 <1069543@85c56323-6fa9-3386-8a01-6480fb634889>
CC: Gerrit User 1041813 <1041813@85c56323-6fa9-3386-8a01-6480fb634889>