ANDROID: rust: allow zero init for KABI members
Allow all-zero initialization for structures that have KABI padding
added. Otherwise, the new __kabi_reserved* fields would need to be
individually initialized. This fixes reported errors such as:

  error[E0063]: missing field `__kabi_reserved1` in initializer of `blk_mq_ops`
     --> /proc/self/cwd/common/rust/kernel/block/mq/operations.rs:216:42
      |
  216 |     const VTABLE: bindings::blk_mq_ops = bindings::blk_mq_ops {
      |                                          ^^^^^^^^^^^^^^^^^^^^ missing `__kabi_reserved1`

Bypass-Upstream-Divergence-Tracking

Bug: 151154716
Cc: Alice Ryhl <aliceryhl@google.com>
Cc: Matthew Maurer <mmaurer@google.com>
Cc: Greg Kroah-Hartman <gregkh@google.com>
Change-Id: If7996037e95b3947eb3b3afa9513cff18f4be116
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Signed-off-by: Mateusz Urbańczyk <urbanczyk@google.com>