um: x86_64: defconfig: disable CONFIG_WERROR
CONFIG_WERROR enabled by default for all builds, that is causing
build failure for 'arch = um' with below errors, so disabling it.

arch/um/os-Linux/signal.c: In function ‘sig_handler_common’:
arch/um/os-Linux/signal.c:51:1: error: the frame size of 2960 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 }
 ^
arch/um/os-Linux/signal.c: In function ‘timer_real_alarm_handler’:
arch/um/os-Linux/signal.c:95:1: error: the frame size of 2960 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 }

Change-Id: Ib7474bddfefa97f9c60087db6a607a111e4d23bc
Signed-off-by: Srinivasarao Pathipati <quic_spathi@quicinc.com>