ANDROID: Avoid ABI Breakage
function symbol 'int __traceiter_f2fs_submit_folio_write(void*, struct folio*, struct f2fs_io_info*)' changed
  CRC changed from 0x3f6478e5 to 0xdf0f2fbe

type 'struct f2fs_sb_info' changed
  member 'unsigned int first_zoned_segno' was removed
  member 'unsigned int first_seq_zone_segno' was added

type 'struct sec_entry' changed
  byte size changed from 4 to 8
  member 'unsigned int ckpt_valid_blocks' was added

ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: From out/prebuilt_cached/artifacts/kernel_notrim_aarch64/abi_stgdiff/abi.report.short:

function symbol 'int __traceiter_f2fs_submit_folio_write(void*, struct folio*, struct f2fs_io_info*)' changed
  CRC changed from 0x3f6478e5 to 0xdf0f2fbe

type 'struct f2fs_sb_info' changed
  member 'unsigned int first_zoned_segno' was removed
  member 'unsigned int first_seq_zone_segno' was added

type 'struct sec_entry' changed
  byte size changed from 4 to 8
  member 'unsigned int ckpt_valid_blocks' was added

Bug: 407985454
Change-Id: I09f5c72c87301e6c833d59b57cc44ec9596e9c23
Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>