ANDROID: db845c KABI update for QCOM_COMMAND_DB as a module
Generated with:
      BUILD_CONFIG=common/build.config.db845c build/build_abi.sh -s

NOTE: This isn't quite sufficient as I'm still seeing the
following build errors:

Comparing the KMI and the symbol lists:
+ /home/docker/repo/build/abi/compare_to_symbol_list
/home/docker/repo/out/android12-5.4/common/Module.symvers
/home/docker/repo/out/android12-5.4/common/abi_symbollist.raw
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - cmd_db_read_addr
 - cmd_db_read_aux_data
 - cmd_db_read_slave_id
 - cmd_db_ready
Symbols missing from symbol list:

Bug: 161128971
Change-Id: I41274db59c71390dd95470a65c1c8da441c83b1e
Signed-off-by: John Stultz <john.stultz@linaro.org>