Revert "ANDROID: abi_gki_aarch64_qcom: update abi symbols"
Revert addition of restricted vendor hook for cpu_capacity_show

Reason for revert: 

This breaks the microdroid build with

```
ERROR: common/BUILD.bazel:166:13: Building kernel (lto=default;notrim) @@//common:kernel_aarch64_microdroid failed: (Exit 2): bash failed: error executing KernelBuild command (from target //common:kernel_aarch64_microdroid) /bin/bash -c ... (remaining 1 argument skipped)

common/drivers/base/arch_topology.c:226:2: error: call to undeclared function 'trace_android_rvh_cpu_capacity_show'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
226 | trace_android_rvh_cpu_capacity_show(&capacity, cpu->dev.id);
| ^
1 error generated.
```

Reverted changes: /q/submissionid:3058744

Change-Id: Ide6f2eddffd8c633e607afb861b663c5b1ac702c