ANDROID: power_supply: Change parameter type power_supply_class inline with recent conversion
Commit 71c2cc5cbf68 ("power: supply: core: make power_supply_class
constant") constified power_supply_class and started passing it around
by reference.  This commit brings our out-of-tree code back inline with
the API.

Fixes the following compiler error:

  drivers/power/supply/power_supply_core.c:605:30: error:
    passing 'const struct class' to parameter of incompatible type 'const struct class *'; take the address with &
      605 |         ret = class_for_each_device(power_supply_class, NULL, &param,
          |                                     ^~~~~~~~~~~~~~~~~~
          |                                     &

Fixes: dea1a925f6a1 ("ANDROID: power_supply: Add a helper function to retrieve psy array from phandle")
Fixes: 71c2cc5cbf68 ("power: supply: core: make power_supply_class constant")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Ifbc7e67499174a405a635c519ced99a57c70e819