ANDROID: GKI: update abi_gki_protected_exports_aarch64
Running tools/bazel run //common:kernel_aarch64_abi_update resultedi
in error below.

ERROR: protected exports list must be updated before updating ABI definition.
To update, execute 'tools/bazel run @@//common:kernel_aarch64_abi_update_protected_exports'.

Fix this by running kernel_aarch64_abi_update_protected_exports.

Fixes: 546eba0b1098 ("nfc: nci: Fix race between rfkill and nci_unregister_device().")
Change-Id: I23131aac48e5a8c979547c9c44341f481cca58a8
Signed-off-by: Sooyong Suk <s.suk@samsung.corp-partner.google.com>