ANDROID: Fix uninitialized 'done' in scmi_cpufreq
Fix the following KernelCI build error when compiling with gcc:

drivers/cpufreq/scmi-cpufreq.c: In function ‘scmi_limit_notify_cb’:
drivers/cpufreq/scmi-cpufreq.c:198:13: error: ‘done’ is used uninitialized [-Werror=uninitialized]
  198 |         if (done)
      |             ^~~~
drivers/cpufreq/scmi-cpufreq.c:193:14: note: ‘done’ was declared here
  193 |         bool done;
      |              ^~~~
cc1: all warnings being treated as errors
make[4]: *** [scripts/Makefile.build:240: drivers/cpufreq/scmi-cpufreq.o] Error 1

Fixes: a475a3d8e54f ("ANDROID: scmi_cpufreq: Add restricted vendor hook
for scmi_limit_notify_cb")
Change-Id: I12b4651aaa2f95e120fd8ce6dcddfd36d6d6373d
Signed-off-by: Tiffany Yang <ynaffit@google.com>