ANDROID: kleaf: Rename kernel module diag.ko to tipc_diag.ko
Commit 06e6bc1b7aaf ("tipc: rename the module name diag to tipc_diag")
renamed the output file diag.ko to tipc_diag.ko.  This commit informs
Bazel of the change.

Fixes the following error:

  ERROR: Unable to find net/tipc/diag.ko in any of the following directories:
  bazel-out/k8-fastbuild/bin/common/kernel_aarch64/staging/lib/modules/6.9.0-rc1-mainline-g1025716457ad-abP72933478/kernel

Fixes: 06e6bc1b7aaf ("tipc: rename the module name diag to tipc_diag")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Id4e4f45e9db82ee16a20f94e8b857a4c5cc75819