ANDROID: abi: Update abi.stg
It seems that the stg file was not in-sync. Let's update it.

ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: Report summary:

variable symbol changed from 'struct snd_soc_acpi_mach snd_soc_acpi_intel_lnl_sdw_machines[13]' to 'struct snd_soc_acpi_mach snd_soc_acpi_intel_lnl_sdw_machines[17]'
  CRC changed from 0xf926fd40 to 0xa6addfca
  type changed from 'struct snd_soc_acpi_mach[13]' to 'struct snd_soc_acpi_mach[17]'
    number of elements changed from 13 to 17

variable symbol changed from 'struct snd_soc_acpi_mach snd_soc_acpi_intel_mtl_sdw_machines[20]' to 'struct snd_soc_acpi_mach snd_soc_acpi_intel_mtl_sdw_machines[21]'
  CRC changed from 0xc74c1ef0 to 0x7f674521
  type changed from 'struct snd_soc_acpi_mach[20]' to 'struct snd_soc_acpi_mach[21]'
    number of elements changed from 20 to 21

variable symbol changed from 'struct snd_soc_acpi_mach snd_soc_acpi_intel_ptl_sdw_machines[10]' to 'struct snd_soc_acpi_mach snd_soc_acpi_intel_ptl_sdw_machines[17]'
  CRC changed from 0x10a842a1 to 0xa6addfca
  type changed from 'struct snd_soc_acpi_mach[10]' to 'struct snd_soc_acpi_mach[17]'
    number of elements changed from 10 to 17

function symbol changed from 'bool snd_soc_acpi_sdw_link_slaves_found(struct device*, const struct snd_soc_acpi_link_adr*, struct sdw_extended_slave_id*, int)' to 'bool snd_soc_acpi_sdw_link_slaves_found(struct device*, const struct snd_soc_acpi_link_adr*, struct sdw_peripherals*)'
  CRC changed from 0x74d6d6d8 to 0xa4a58f94
  type changed from 'bool(struct device*, const struct snd_soc_acpi_link_adr*, struct sdw_extended_slave_id*, int)' to 'bool(struct device*, const struct snd_soc_acpi_link_adr*, struct sdw_peripherals*)'
    parameter 3 type changed from 'struct sdw_extended_slave_id*' to 'struct sdw_peripherals*'
      pointed-to type changed from 'struct sdw_extended_slave_id' to 'struct sdw_peripherals'
    parameter 4 of type 'int' was removed

function symbol 'int snd_intel_acpi_dsp_driver_probe(struct device*, const u8*)' changed
  CRC changed from 0x7eb81ba6 to 0x8c46f101

function symbol 'int snd_intel_dsp_driver_probe(struct pci_dev*)' changed
  CRC changed from 0x2f6c4a8b to 0xa672e017

function symbol 'struct snd_soc_acpi_mach* snd_soc_acpi_find_machine(struct snd_soc_acpi_mach*)' changed
  CRC changed from 0x67511da7 to 0x65ebc0fb

... 31 omitted; 34 symbols have only CRC changes

type 'struct snd_soc_acpi_mach' changed
  byte size changed from 192 to 208
  member 'bool(* machine_check)(void*)' was added
  4 members ('void* pdata' .. 'const u32 tplg_quirk_mask') changed
    offset changed by 64
  member 'int(* get_function_tplg_files)(struct snd_soc_card*, const struct snd_soc_acpi_mach*, const char*, const char***)' was added

Bug: 442414507
Test: tools/bazel run //common:kernel_x86_64_abi_update

Change-Id: Ifd4e773cf305d20f0982c418e21b5c93696da9d4
Signed-off-by: Ricardo Ribalda <ribalda@google.com>