FROMLIST: rcu-tasks: Fix build error
All warnings are treated as errors with the patch
824c555 ("UPSTREAM: Enable '-Werror' by default for all kernel builds").
Fixing below build error that got poped up due to this patch by
making show_rcu_tasks_rude_gp_kthread() function as 'inline'.

This is applicable to only 5.10 kernels as code got modified
in latest kernels.

 In file included from kernel/rcu/update.c:579:0:
 kernel/rcu/tasks.h:710:13: error: ‘show_rcu_tasks_rude_gp_kthread’ defined but not used [-Werror=unused-function]
  static void show_rcu_tasks_rude_gp_kthread(void) {}

Bug: 269057599
Link: https://lore.kernel.org/stable/1676916839-32235-1-git-send-email-quic_c_spathi@quicinc.com/
Fixes: 8344496e8b49 ("rcu-tasks: Conditionally compile show_rcu_tasks_gp_kthreads()")
Change-Id: I95f6a7a81883d7a6b0f56068b1eb49dc02788685
Signed-off-by: Srinivasarao Pathipati <quic_spathi@quicinc.com>