ANDROID: Update abi_gki_protected_exports_aarch64
Running
 tools/bazel run //common:kernel_aarch64_abi_update

I saw the following error:
 ERROR: protected exports list must be updated before updating ABI definition.
 To update, execute 'tools/bazel run @@//common:kernel_aarch64_abi_update_protected_exports'.

So this is the result of running kernel_aarch64_abi_update_protected_exports

Change-Id: I6fdbc2ecf9c74dd069fd33dec3c39762c7a0fd45
Signed-off-by: John Stultz <jstultz@google.com>