ANDROID: mm: Rename tracepoint symbol for brevity
During the compilation of the driver, I encountered an error:
ERROR: modpost: too long symbol "android_vh_filemap_fault_before_folio_locked"

Changed the tracepoint symbol __tracepoint_android_vh_filemap_fault_before_folio_locked
to __tracepoint_android_vh_filemap_fault_bf_locked to comply with symbol length constraints
in the kernel.

Bug: 417133503
Bug: 429592429
Fixes: 75fcaabc132a ("ANDROID: mm: add vendor hook to activate/unactivate folios")
Change-Id: I836b9f79f808bf121823c9d5fc4a1665fdac30a9
Signed-off-by: Tangquan Zheng <zhengtangquan@oppo.com>
(cherry picked from commit b7dfd1f443bf08c12b30af7707732694c3cdbb50)
Signed-off-by: Hailong Liu <hailong.liu@oppo.com>