ANDROID: rust_binder: Fix missing-prototypes warnings
Fix missing-prototypes warnings and remove the unused function
is_rust_binderfs_device().

Also remove the definition of rust_binder_context and binder_device from
rust_binder.h as they are duplicated from rust_binder_internal.h.

Fix the following missing-prototypes warnings:
/.../drivers/android/binder/page_range_helper.c:21:1: error: no previous prototype for function 'rust_shrink_free_page_wrap' [-Werror,-Wmissing-prototypes]
   21 | rust_shrink_free_page_wrap(struct list_head *item, struct list_lru_one *list,
      | ^
/.../drivers/android/binder/page_range_helper.c:20:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
   20 | enum lru_status
      | ^
      | static
1 error generated.
/.../scripts/Makefile.build:240: drivers/android/binder/page_range_helper.o] Error 1
make[5]: *** Waiting for unfinished jobs....
/.../drivers/android/binder/rust_binderfs.c:95:6: error: no previous prototype for function 'is_rust_binderfs_device' [-Werror,-Wmissing-prototypes]
   95 | bool is_rust_binderfs_device(const struct inode *inode)
      |      ^
/.../drivers/android/binder/rust_binderfs.c:95:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
   95 | bool is_rust_binderfs_device(const struct inode *inode)
      | ^
      | static
/.../drivers/android/binder/rust_binderfs.c:500:6: error: no previous prototype for function 'rust_binderfs_remove_file' [-Werror,-Wmissing-prototypes]
  500 | void rust_binderfs_remove_file(struct dentry *dentry)
      |      ^
/.../drivers/android/binder/rust_binderfs.c:500:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  500 | void rust_binderfs_remove_file(struct dentry *dentry)
      | ^
      | static
/.../drivers/android/binder/rust_binderfs.c:515:16: error: no previous prototype for function 'rust_binderfs_create_file' [-Werror,-Wmissing-prototypes]
  515 | struct dentry *rust_binderfs_create_file(struct dentry *parent, const char *name,
      |                ^
/.../drivers/android/binder/rust_binderfs.c:515:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  515 | struct dentry *rust_binderfs_create_file(struct dentry *parent, const char *name,
      | ^
      | static
/.../drivers/android/binder/rust_binderfs.c:548:16: error: no previous prototype for function 'rust_binderfs_create_proc_file' [-Werror,-Wmissing-prototypes]
  548 | struct dentry *rust_binderfs_create_proc_file(struct inode *nodp, int pid)
      |                ^
/.../drivers/android/binder/rust_binderfs.c:548:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  548 | struct dentry *rust_binderfs_create_proc_file(struct inode *nodp, int pid)
      | ^
      | static
/.../drivers/android/binder/rust_binderfs.c:828:5: error: no previous prototype for function 'init_rust_binderfs' [-Werror,-Wmissing-prototypes]
  828 | int init_rust_binderfs(void)
      |     ^
/.../drivers/android/binder/rust_binderfs.c:828:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  828 | int init_rust_binderfs(void)
      | ^
      | static
5 errors generated.

Bug: 425609355
Change-Id: I4f9f0b8b17795cb88d0a4c5816081598dd98be95
Signed-off-by: Jacky Liu <qsliu@google.com>