ANDROID: Update abi.stg definitions
Update the abi.stg file since new symbol was added to the drm_bridge
struct. ABI diff report as follows:

ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: Report summary:

function symbol 'void __drm_atomic_helper_bridge_duplicate_state(struct drm_bridge*, struct drm_bridge_state*)' changed
  CRC changed from 0x9ed85f5c to 0x845827d4

function symbol 'void __drm_atomic_helper_bridge_reset(struct drm_bridge*, struct drm_bridge_state*)' changed
  CRC changed from 0x9ed85f5c to 0x845827d4

function symbol 'int devm_drm_bridge_add(struct device*, struct drm_bridge*)' changed
  CRC changed from 0xeb9c29ea to 0x7b1667d5

... 32 omitted; 35 symbols have only CRC changes

type 'struct drm_bridge' changed
  member 'bool support_hdcp' was added

Bug: 438243152
Change-Id: Ib54954c1309e2a8bca73d7e441fa25829ac621eb
Signed-off-by: Hubert Mazur <hmazur@google.com>