Revert "lib: Fix ia64 bootloader linkage"
This reverts commit 93048c0944150b316a15f92c41a4d626c8df37fd in order to
temporarily work around a x86_64 allmodconfig breakage:

   ERROR: "__memcat_p" [drivers/hwtracing/stm/stm_core.ko] undefined!

Bug: 140224784
Test: Successful build with build.config.allmodconfig.x86_64
Signed-off-by: Quentin Perret <qperret@google.com>
Change-Id: I443b5e48fcfea0a448de99bd54f6c82c078124e5