ANDROID: fix GCMA build failure when CONFIG_RANDSTRUCT=y
allmodconfig builds fail with the error:

mm/gcma.c:53:9: error: casting from randomized structure pointer type 'struct address_space *' to 'struct gcma_inode *'
   53 |         return (struct gcma_inode *)page->mapping;

This happens when structure randomization is enabled because page->mapping
structure is randomized. Work around this failure by casting to void*.
Similar approach has been used in other places in the kernel, for example:

https://lore.kernel.org/all/20230616012136.3047071-1-yukuai1@huaweicloud.com/

Bug: 487317658
Bug: 391879760
Change-Id: I2cd77330ebaa7189c831f8451b7199f928e789db
Signed-off-by: Suren Baghdasaryan <surenb@google.com>