BACKPORT: drm/xe/xe_gt_idle: add debugfs entry for powergating info
Coarse Powergating is a power saving technique where Render and Media
can be power-gated independently irrespective of the rest of the GT.

For debug purposes, it is useful to expose the powergating information.

v2: move to debugfs
    add details to commit message
    add per-slice status for media
    define reg bits in descending order (Matt Roper)

v3: fix return statement
    fix kernel-doc
    use loop for media slices
    use helper function for status (Michal)

v4: add pg prefix
    do not wake GT if in C6 (Badal)

Signed-off-by: Riana Tauro <riana.tauro@intel.com>
Reviewed-by: Badal Nilawar <badal.nilawar@intel.com>
Acked-by: Rodrigo Vivi <rodrigo.vivi@intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20240906071126.28078-3-riana.tauro@intel.com
Signed-off-by: Rodrigo Vivi <rodrigo.vivi@intel.com>
(cherry picked from commit 0914c1e45d3a1a747faeebae27ba197d7ba41f94)

Backport Notes:
---------------
'str_up_down' function got removed as a part of the following merge commit
from Linux Torvalds repo to fix the build failure from backmerge

b88132ceb3faccdd785809df75f9d490ebaab459 "Merge drm/drm-next into
drm-xe-next"

drivers/gpu/drm/xe/xe_gt_idle.c:56:27: error: redefinition of
'str_up_down'
   56 | static inline const char *str_up_down(bool v)
      |                           ^
./include/linux/string_choices.h:62:27: note: previous definition is
here
   62 | static inline co  CC [M]
      drivers/gpu/drm/i915/gt/uc/intel_guc_ct.o
nst char *str_up_down(bool v)
      |                           ^

Bug: 406266020
Bug: 387910155
Upstream-Task: 412788966
Test: DUT booted to UI

Change-Id: I7e373e96c67e24950794ee4dddfadd11757cb25b
Signed-off-by: George D Sworo <george.d.sworo@intel.corp-partner.google.com>
Signed-off-by: Ryan Neph <ryanneph@google.com>