ANDROID: sched: Add missing prototypes of exported functions
Due to this commit, 532bb17ab5dfef4ffab916e3e0343e009cbad80a,
__balance_callbacks and set_next_entity functions exported by
vendors are causing the following build issue:

common/kernel/sched/core.c:5186:6: error: no previous prototype for
function '__balance_callbacks' [-Werror,-Wmissing-prototypes]

common/kernel/sched/fair.c:5579:6: error: no previous prototype
for function 'set_next_entity' [-Werror,-Wmissing-prototypes]

Fix this by including prototypes for these functions.

Signed-off-by: Sai Harshini Nimmala <quic_snimmala@quicinc.com>
Change-Id: I0b0293c03432e07986822c5fba5bbeab6d4127af