ANDROID: fuse-bpf: Fix build breakage without CONFIG_FUSE_BPF
Fix build error if CONFIG_FUSE_BPF not defined:

common/fs/fuse/file.c:2771:20: error: unused variable 'ff' [-Werror,-Wunused-variable]
2771 | struct fuse_file *ff = in->private_data;
| ^~
1 error generated.

Fixes: 5fb8f1c931c2 ("ANDROID: fuse-bpf: add bpf solution for splice read")
Change-Id: I43d194a1d326fd61c5faafbb524f6ca484fb29f6
Signed-off-by: Paul Lawrence <paullawrence@google.com>