ANDROID: ABI: remove stale symbol
The following symbol no longer exists after backporting upstream commit
6fd1d51cfa25 ("net: SO_RCVMARK socket option for SO_MARK with
recvmsg()"). Removing the symbol fixes the following KMI build issue:

Symbols missing from the ksymtab:
  __sock_recv_ts_and_drops
ERROR: Checking for kmi_symbol_list_strict_mode

Bug: 285364323
Cc: zhangao <zhangao@zeku.com>
Change-Id: I53038b3561c0d758b908307ea17d3f9c8c2ec472
Signed-off-by: Carlos Llamas <cmllamas@google.com>