Update patch set 2
Patch Set 2:

This patch caused a kernelci build-break for 32-bit builds. See https://kernelci.org/build/id/5ef16b04565f76004797bf1c/logs/

Errors:

../include/linux/extcon.h:316:1: warning: data definition has no type or storage class
 EXPORT_SYMBOL_GPU(extcon_get_edev_name);
 ^~~~~~~~~~~~~~~~~
../include/linux/extcon.h:316:1: error: type defaults to ‘int’ in declaration of ‘EXPORT_SYMBOL_GPU’ [-Werror=implicit-int]
../include/linux/extcon.h:316:1: warning: parameter names (without types) in function declaration
cc1: some warnings being treated as errors
make[2]: *** [../scripts/Makefile.build:333: arch/arm/mach-pxa/devices.o] Error 1

Please submit a fix.

Patch-set: 2
CC: Gerrit User 1069543 <1069543@85c56323-6fa9-3386-8a01-6480fb634889>