ANDROID: ftrace: fix build issue
Fix below compilation errors by forward declaration of struct trace_seq.

  include/trace/hooks/ftrace_dump.h:29:18: error: \
  declaration of 'struct trace_seq' will not be visible \
  outside of this function [-Werror,-Wvisibility]

  include/trace/hooks/ftrace_dump.h:30:10: error: incompatible \
  pointer types passing 'struct trace_seq *' to parameter of type \
  'struct trace_seq *' [-Werror,-Wincompatible-pointer-types]

Fixes: ebc2d04428e58 ("ANDROID: ftrace: add more vendor hook for ftrace dump on oops")
Bug: 177387994
Change-Id: I9866e4cc9466e77c5deaf8d644f4048c802b82c1
Signed-off-by: Satya Durga Srinivasu Prabhala <quic_satyap@quicinc.com>