ANDROID: GKI: update the ABI symbol list
ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: 1 function symbol(s) added
  'int __traceiter_android_rvh_entity_tick(void*, struct cfs_rq*, struct sched_entity*)'

1 variable symbol(s) added
  'struct tracepoint __tracepoint_android_rvh_entity_tick'

function symbol 'void __balance_callbacks(struct rq*)' changed
  CRC changed from 0xaba29c8d to 0xabc35040

function symbol 'int __cpufreq_driver_target(struct cpufreq_policy*, unsigned int, unsigned int)' changed
  CRC changed from 0x9032f0f4 to 0x4373da2

function symbol 'struct rq* __migrate_task(struct rq*, struct rq_flags*, struct task_struct*, int)' changed
  CRC changed from 0x1bba00be to 0x2a09541a

... 655 omitted; 658 symbols have only CRC changes

type 'struct freq_qos_request' changed
  byte size changed from 56 to 64
  member 'u64 android_oem_data1' was added

type 'struct dev_pm_qos_request' changed
  byte size changed from 72 to 80
  member 'union { struct plist_node pnode; struct pm_qos_flags_request flr; struct freq_qos_request freq; } data' changed
    type 'union { struct plist_node pnode; struct pm_qos_flags_request flr; struct freq_qos_request freq; }' changed
      byte size changed from 56 to 64
  member 'struct device* dev' changed
    offset changed by 64

type 'struct devfreq' changed
  byte size changed from 1992 to 2008
  member 'struct dev_pm_qos_request user_max_freq_req' changed
    offset changed by 64
  11 members ('unsigned long scaling_min_freq' .. 'struct notifier_block nb_max') changed
    offset changed by 128

Bug: 339371220

Change-Id: I7d89b7d035645ae9f0874525978acfe5b94e38b9
Signed-off-by: wang qiankun <wangqiankun3@xiaomi.corp-partner.google.com>