um: fix build errors
Now CONFIG_WERROR is enabled by default for all builds that is
causing build failure due to below warnings for 'arch = um'
so fixing these warnings.

arch/um/os-Linux/signal.c: In function ‘sig_handler_common’:
arch/um/os-Linux/signal.c:51:1: error: the frame size of 2960 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 }
 ^
arch/um/os-Linux/signal.c: In function ‘timer_real_alarm_handler’:
arch/um/os-Linux/signal.c:95:1: error: the frame size of 2960 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 }

kernel/rcu/tasks.h:710:13: error: ‘show_rcu_tasks_rude_gp_kthread’ defined but not used [-Werror=unused-function]
 static void show_rcu_tasks_rude_gp_kthread(void) {}

Bug: 269057599
Change-Id: Ib7474bddfefa97f9c60087db6a607a111e4d23bc
Signed-off-by: Srinivasarao Pathipati <quic_spathi@quicinc.com>