ANDROID: Fix up kabi after scheduler changes for thaw
ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: Report summary:

function symbol 'void __balance_callbacks(struct rq*)' changed
  CRC changed from 0x908f8571 to 0xbdeef253

function symbol 'struct rq* __migrate_task(struct rq*, struct rq_flags*, struct task_struct*, int)' changed
  CRC changed from 0xb5bcd07a to 0xa5d626be

function symbol 'struct rq* __task_rq_lock(struct task_struct*, struct rq_flags*)' changed
  CRC changed from 0x9371bba6 to 0xe2c1994f

... 150 omitted; 153 symbols have only CRC changes

type 'struct cfs_rq' changed
  member 'unsigned int nr_running' was removed
  member 'unsigned int nr_queued' was added
  member 'unsigned int idle_nr_running' was removed
  member 'unsigned int idle_h_nr_running' was removed
  member 'unsigned int h_nr_delayed' was removed
  member 'unsigned int h_nr_idle' was added
  6 members ('s64 avg_vruntime' .. 'struct sched_entity* next') changed
    offset changed by -64

Change-Id: I6956dac83c084d7ea832bbe194918f3a2330a65e
Signed-off-by: John Stultz <jstultz@google.com>