ANDROID: perf: Fix perf_event_{init,exit}_cpu stubs
After commit ca927bd22ad8 ("ANDROID: cpu/hotplug: avoid breaking Android
ABI by fusing cpuhp steps") a build error would appear with
CONFIG_PERF_EVENTS disabled:

In file included from ./include/uapi/linux/posix_types.h:5,
                 from ./include/uapi/linux/types.h:14,
                 from ./include/linux/types.h:6,
                 from ./include/linux/limits.h:6,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/sched/mm.h:5,
                 from kernel/cpu.c:6:
kernel/cpu.c: In function 'random_and_perf_prepare_fusion':
./include/linux/stddef.h:8:14: error: called object is not a function or function pointer
 #define NULL ((void *)0)
              ^
./include/linux/perf_event.h:1607:29: note: in expansion of macro 'NULL'
 #define perf_event_init_cpu NULL
                             ^~~~
kernel/cpu.c:1686:2: note: in expansion of macro 'perf_event_init_cpu'
  perf_event_init_cpu(cpu);
  ^~~~~~~~~~~~~~~~~~~
  CC      kernel/power/console.o
make[1]: *** [scripts/Makefile.build:287: kernel/cpu.o] Error 1
make[1]: *** Waiting for unfinished jobs....

Fix this by using proper stubs. The original commit that introduced
those stubs was already at fault, but in the absence of a caller of
perf_event_{init,exit}_cpu outside of code that is compiled regardless
of CONFIG_PERF_EVENTS, the build failure cannot be observed.

Fixes: ca927bd22ad8 ("ANDROID: cpu/hotplug: avoid breaking Android ABI by fusing cpuhp steps")
Fixes: 00e16c3d68fc ("perf/core: Convert to hotplug state machine")
Reported-by: Anand Gore <anand.gore@broadcom.com>
Signed-off-by: Florian Fainelli <florian.fainelli@broadcom.com>
Change-Id: I1e93284b40b3e13302a7fcc10d72d4702b856e8b