ANDROID: GKI: update the ABI symbol list
ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: 4 function symbol(s) added
  'int __traceiter_android_vh_alloc_uid(void*, struct user_struct*)'
  'int __traceiter_android_vh_free_user(void*, struct user_struct*)'
  'struct user_struct* find_user(kuid_t)'
  'void free_uid(struct user_struct*)'

2 variable symbol(s) added
  'struct tracepoint __tracepoint_android_vh_alloc_uid'
  'struct tracepoint __tracepoint_android_vh_free_user'

variable symbol 'const struct dwc3* const ANDROID_GKI_struct_dwc3' changed
  CRC changed from 0x5338ac0d to 0x380bd175

function symbol 'struct block_device* I_BDEV(struct inode*)' changed
  CRC changed from 0xb374763a to 0x5c32c896

function symbol 'void __ClearPageMovable(struct page*)' changed
  CRC changed from 0xd2ab62a7 to 0xede641dc

... 4558 omitted; 4561 symbols have only CRC changes

type 'struct user_struct' changed
  byte size changed from 152 to 168
  member 'u64 android_oem_data1[2]' was added

Bug: 339371220

Change-Id: Id9fccdcb9550c0a1e66ff98d8dcb0218ab995e58
Signed-off-by: wang qiankun <wangqiankun3@xiaomi.corp-partner.google.com>