Revert "ANDROID: zram: Fix build issue with zram_can_store_pages w/o CONFIG_ZRAM_ANDROID_IOCTL"
This reverts commit 487e818b8c0f11de2d03896c8cb09695003a2f59.

Build error when CONFIG_ZRAM_ANDROID_IOCTL is disabled:
  error: call to undeclared function 'zram_can_store_page'

Bug: 495197959
Change-Id: Ica51ee0781361f60dbdb356ad06836b1b6c30f7d
Signed-off-by: Richard Chang <richardycc@google.com>