ANDROID: Fix ‘one_thousand’ defined but not used warning
Fix the following warning issued when CONFIG_PERF_EVENTS is not undefined:
kernel/sysctl.c:124:12: error: ‘one_thousand’ defined but not used [-Werror=unused-variable]

Fixes: 8fded571e739 ("FROMGIT: mm/pagealloc: sysctl: change watermark_scale_factor max limit to 30%")
Bug: 194652782
Signed-off-by: Suren Baghdasaryan <surenb@google.com>
Change-Id: I5539a2d0d27a126f7405455a8cf08c23b80d2e0b