ANDROID: fix kernelci build break: redefinition of 'kallsyms_on_each_symbol'
An extra definition of the function 'kallsyms_on_each_symbol' crept in
for the !KALLSYMS case as a result of the revert of the 5.10.220 merge
combined with the subsequent merge of 5.10.226.

kbuild.compiler.error ./include/linux/kallsyms.h:167:19: error: redefinition
of 'kallsyms_on_each_symbol' in arch/x86/kernel/asm-offsets.s (arch/x86/kernel/asm-offsets.c)

Removed obsolete declaration.

Fixes: 88eb084d18c6 ("Revert Merge 5.10.220 into android12-5.10-lts")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Ieb332a4693aa3f1123e74a719d46fc9e1d083eda