ANDROID: x86: pkvm: Export pkvm_guest_detected
When we build with CONFIG_PKVM_GUEST, this symbol is used by different
modules. It needs to be exported.

Fixes this compile error:
ERROR: modpost: "pkvm_guest_detected" [drivers/ptp/ptp_kvm.ko] undefined!

Test: tools/bazel run //common:kernel_x86_64_dist
Bug: 444310763

Change-Id: I5c1fc9059bcd0be79db360db969db938852d8c2d
Signed-off-by: Ricardo Ribalda <ribalda@google.com>