ANDROID: PM / suspend: Resupply define for REC_FAILED_NUM
Commit 9ff544fa5f94 ("PM: sleep: stats: Define suspend_stats next to the
code using it") moved the original define from include/linux/suspend.h
and placed it inside the only C-file that uses it in Mainline, causing
our out-of-tree Wakeup Reason goodness to result in the following
compile errors:

  kernel/power/suspend.c:424:46: error: use of undeclared identifier 'REC_FAILED_NUM'
    424 |                 last_dev = suspend_stats.last_failed_dev + REC_FAILED_NUM - 1;
        |                                                            ^
  kernel/power/suspend.c:425:15: error: use of undeclared identifier 'REC_FAILED_NUM'
    425 |                 last_dev %= REC_FAILED_NUM;
        |                 ^

Fixes: bc17c02a8507 ("ANDROID: power: wakeup_reason: add an API to log wakeup reasons")
Fixes: 9ff544fa5f94 ("PM: sleep: stats: Define suspend_stats next to the code using it")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I1f60e9d0371c65bf5dabcf469636f720672bb341