BACKPORT: FIXUP: Redefinition error of 'str_up_down' function
'str_up_down' function got removed as a part of the following merge commit
from Linux Torvalds repo to fix the build failure from backmerge

b88132ceb3faccdd785809df75f9d490ebaab459 "Merge drm/drm-next into
drm-xe-next"

drivers/gpu/drm/xe/xe_gt_idle.c:56:27: error: redefinition of
'str_up_down'
   56 | static inline const char *str_up_down(bool v)
      |                           ^
./include/linux/string_choices.h:62:27: note: previous definition is
here
   62 | static inline co  CC [M]
      drivers/gpu/drm/i915/gt/uc/intel_guc_ct.o
nst char *str_up_down(bool v)
      |                           ^

BUG: 387910155
TEST: DUT booted to UI

Change-Id: Ic0cb00f4f8e7fdad70772a9bcb117c0672573183
Signed-off-by: George D Sworo <george.d.sworo@intel.corp-partner.google.com>