ANDROID: GKI: Put vendor_data_pad behind CONFIG_GKI_DYNAMIC_TASK_STRUCT_SIZE
vendor_data_pad uses CONFIG_GKI_TASK_STRUCT_VENDOR_SIZE_MAX, which is
only defined when CONFIG_GKI_DYNAMIC_TASK_STRUCT_SIZE is enabled,
resulting in build failures when it is not:

  In file included from arch/arm/kernel/asm-offsets.c:12:
  In file included from include/linux/mm.h:1120:
  In file included from include/linux/huge_mm.h:8:
  In file included from include/linux/fs.h:33:
  In file included from include/linux/percpu-rwsem.h:7:
  In file included from include/linux/rcuwait.h:6:
  In file included from include/linux/sched/signal.h:9:
  include/linux/sched/task.h:59:28: error: use of undeclared identifier 'CONFIG_GKI_TASK_STRUCT_VENDOR_SIZE_MAX'
     59 | extern u64 vendor_data_pad[CONFIG_GKI_TASK_STRUCT_VENDOR_SIZE_MAX / sizeof(u64)];
        |                            ^
  1 error generated.

Place all instances of vendor_data_pad behind
CONFIG_GKI_DYNAMIC_TASK_STRUCT_SIZE to address the build failures.

This commit is a revert of dcd4445f92f8df8864ef9e57a6d17e11c40dc6c6,
which is a revert in itself. So essentially, this commit brings back the
original change.

Bug: 233921394
Fixes: 1827ee5e5a2de3 ("ANDROID: GKI: Add padding after init_task structure")
Fixes: 5e9a8cb7144f7d ("ANDROID: GKI: Add to task_struct size via cmdline")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Sai Harshini Nimmala <snimmala@qti.qualcomm.com>
Change-Id: I79a7b6a9aefc9e9d758d06e3006d851f0b0fbcd7