ANDROID: riscv: gki_defconfig: drop CONFIG_MODULE_SIG_SHA1 and CONFIG_DMABUF_SYSFS_STATS
Both symbols were removed from the upstream Linux Kconfig (SHA1 is no
longer considered acceptable for module signing, and DMABUF_SYSFS_STATS
was folded into DMABUF unconditional accounting).  Keeping them in
arch/riscv/configs/gki_defconfig (inherited from android-mainline-riscv64)
makes kleaf KernelConfig fail with:

  ERROR: CONFIG_MODULE_SIG_SHA1: actual '', expected 'y' from .../gki_defconfig
  ERROR: CONFIG_DMABUF_SYSFS_STATS: actual '', expected 'y' from .../gki_defconfig

Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>