ANDROID: xfs: fix undefined __aeabi_uldivmod build issue
A recently added mult_frac() call in xfs upstream breaks arm builds:

  ERROR: modpost: "__aeabi_uldivmod" [fs/xfs/xfs.ko] undefined!

Luckily Guenter offered a temporary solution in [1] which works for now
while the proper fix for mult_frac() (or xfs) lands upstream.

Cc: Guenter Roeck <groeck@google.com>
Fixes: 845abeb1f06a ("xfs: add tunable threshold parameter for triggering zone GC")
Link: https://lore.kernel.org/all/e5ccf0d5-a757-4d1b-84b9-36a5f02e117c@roeck-us.net/ [1]
Change-Id: I11e98b4d87c04300f84c0ab12f97f3a2add5ac67
Signed-off-by: Carlos Llamas <cmllamas@google.com>