ANDROID: vendor_hooks: rename vh_folios_put_refs_direct_free_extent
I added a vendor hook "vh_folios_put_refs_direct_free_extent" in 'commit
dc31c5748f64 ("ANDROID: vendor_hooks: Add vh_folios_put_refs_direct_free_extent")',
while the hook name is too long and causes a build error when used:

ERROR: modpost: too long symbol "__tracepoint_android_vh_folios_put_refs_direct_free_extent".

The root cause is that in `scripts/mod/modpost.c`, exported symbol names
are checked against `MODULE_NAME_LEN`. The error would not happen if
CONFIG_EXTENDED_MODVERSIONS is enabled.

If 6.18 abi is not frozen, rename it to "vh_folios_put_direct_free"

Bug: 504935225
Change-Id: I462cf42b6d3ff9954bb5618971b5dd7518dec51c
Signed-off-by: Wenchao Hao <haowenchao@xiaomi.corp-partner.google.com>